### ISSUE TITLE
Run error "Segment Dumped"

### ISSUE THREAD

**Issue by legendary-acp** [Kartikay26/MegaChessatron#12]
After successful compilation when I run the program it says Segment Dumped.

**Comment by Kartikay26** [comment]
Can you provide more details? How did you compile the program, on what platform, any input/output, screenshots etc?

**Comment by Kartikay26** [comment]
Apparantly the program requires an opening book to be placed in opening_book.txt ... however I seem to have lost that file. Till then we can disable the opening book feature perhaps?
